### ISSUE TITLE
Mobile devices: Header item (mobilenavConfig hamburger-menu) bug

### ISSUE THREAD

**Issue by 411A** [kwchang0831/svelte-QWER#100]
### Describe the bug

Used emoji on header links, on desktop it's fine, on mobile and hamburger menu it closes the menu when tapping on the link.

### Reproduction

Just open the **https://svelte-qwer.vercel.app** on a mobile phone or simulate dimensions on browser, tap on hamburger menu and select a link... it'll close the menu.

### System Info

```shell
Nothing.
```

**Comment by kwchang0831** [comment]
![issue#100_07072024](https://github.com/kwchang0831/svelte-QWER/assets/88667293/5d2a4ef5-5b24-4953-876e-386f6a50ae8a)

LGTM.

**Comment by 411A** [comment]
Yeah thanks it's fixed now with your latest commit.
