### ISSUE TITLE
Missing .env.example

### ISSUE THREAD

**Issue by SrGeneroso** [kwchang0831/svelte-QWER#21]
I see there is a !.env.example in the .gitignore and also that a .env file is needed for the svelte.config.js adapter choice. 
Since I wanted to use the static adapter I guess I'm ok since it's the default

**Comment by kwchang0831** [comment]
Vercel Env: https://vercel.com/docs/concepts/projects/environment-variables
Static Adapter is the default without any env variable.

It is not required to provide a .env file.
