### ISSUE TITLE
How to change favicon?

### ISSUE THREAD

**Issue by wjwei-handsome** [kwchang0831/svelte-QWER#25]
As the title says, I tried to replace the favicon.[icon,png] in the project, but when I built it, the icon changed back to the original leek, and I was wondering how to customize it?

**Comment by kwchang0831** [comment]
Replace both the `user/public/favicon.png` and `user/public/favicon.ico`

In case you need this: https://favicon.io/favicon-converter/

**Comment by kwchang0831** [comment]
Thanks for the feedback. 

I have updated my [doc](https://docs-svelte-qwer.vercel.app/customize/quick-start).

Please let me know if you need any help :D

**Comment by wjwei-handsome** [comment]
> 

Thank you for your quick response, QWER is a great work! I have applied it as my personal blog and I am so willing to recommend it to my friends! 😊
