### ISSUE TITLE
Colde Block highlight not work for python

### ISSUE THREAD

**Issue by wjwei-handsome** [kwchang0831/svelte-QWER#26]
I created a demo post, and write:

```python
/// title: example.py
/// showLineNumber
for i in range(10):
    print(i)
```

But it only has black-white color, different with your demo(typescript-helloworld.ts)
I noticed that only defined the code parser of language-typescript and language-javascript (QWER-mdify-parser)
For other users, i think code block highlight for other language is necessary.
As a frond-end novice, i tried put highlight.js into `app.html`, but it not works. Is there any other better way to use highlight.js

**Comment by kwchang0831** [comment]
I will enable highlight for python...

**Comment by kwchang0831** [comment]
I have imported python language support for Prism highlight as of (7a96bf224d53c5aaebba9f1347e698d5fe0b08cc).

Thanks for the feedback. The demo site is also updated.

```python
for i in range(10):
    print('Hello, World #%s' % (i))
```

**Comment by kwchang0831** [comment]
To use highlight.js in the browser side, you might want to create a custom svelte component for it.
To avoid freezing while it highlights codes, you might also want to use web workers.

You may also check out [Shiki](https://github.com/shikijs/shiki).

Have fun coding <3
