### ISSUE TITLE
Wrong image size

### ISSUE THREAD

**Issue by korzh875** [kwchang0831/svelte-QWER#62]
### Describe the bug

iPhone 10x not displaying images correctly

it is somehow cut off, that with a preview, that after opening

can you check?

### Reproduction

Iphone X
v. 14.4
Browser: Chrome\Safari

### Logs

```shell
There is not
```

### System Info

```shell
There is not
```

### Additional Information

- **Preview**

![photo_2023-04-14_22-06-50](https://user-images.githubusercontent.com/130793155/232137920-05c573ad-2a4f-4403-a6f0-eddda22e35b7.jpg)

- **After open**

 ![photo_2023-04-14_22-06-44](https://user-images.githubusercontent.com/130793155/232137893-57738a06-eda4-4118-a524-15763eb3f5fe.jpg)

- **Android works fine**
![photo_2023-04-14_22-24-01](https://user-images.githubusercontent.com/130793155/232138629-9541fe7e-7e55-4c4b-a343-e0358e507388.jpg)

**Comment by kwchang0831** [comment]
That's interesting. 
I have only Android phone, so I have not tested on actual iPhone.

I just tried https://www.browserstack.com/test-on-iphone. 
iPhone 11/12 works fine. 

hmm... and I noticed some of the older version iPhones do have issues displaying the site.
I currently have no solution.
