### ISSUE TITLE
Jerky animation

### ISSUE THREAD

**Issue by korzh875** [kwchang0831/svelte-QWER#63]
### Describe the bug

Phantom jumps (animation) when you first go to a post or when the Internet is weak

### Reproduction

Windows 11
Chrome 112.05
Desctop\Mobile version

### Logs

```shell
There is not
```

### System Info

```shell
There is not
```

### Additional Information

- **Here I'm trying to show how loading a post for the first time or when the Internet is weak (this becomes not obvious)**

https://user-images.githubusercontent.com/130793155/232141408-421c63b4-cfb8-460c-84fe-94a0addda963.mp4

**Comment by kwchang0831** [comment]
Thanks for reporting this.

This is an known issue.

The service worker will try to install all the assets for the first time, the next time visiting the site should run normally and more smoothly. That's why I have not spent time on trying to figure out a solution for this.

**Comment by korzh875** [comment]
ok, I can somehow fix it locally, but as an option, then the first load, just exclude the animation and leave the loader, it would be right without side effects
