### ISSUE TITLE
Text from Markdown on the main page

### ISSUE THREAD

**Issue by korzh875** [kwchang0831/svelte-QWER#64]
Hello. Thanks for your work.

I want to add text from the markdown template on the main page, how can I do that?

I tried to parse, but somehow it turns out difficult and then there are problems with styles

Could you provide an example?

![Screenshot 2023-04-15 230731](https://user-images.githubusercontent.com/130793155/232251260-1ea3e6be-cbbb-4b4b-a63c-d32ca6486fd8.jpg)

Meaning markup, tables, formatting, structure

**Comment by kwchang0831** [comment]
Since it is static text, why not just write inside [routes/+layout.svelte](https://github.com/kwchang0831/svelte-QWER/blob/main/src/routes/%2Blayout.svelte) ?

**Comment by korzh875** [comment]
I'm not talking about this, or rather not about such a simple use, the implementation meant that the text would be in markdown format

we have an example of a template that is not used in the general list

options:
     - unregistered

and i wish we could add a template like this to the main page (or anywhere else)

options:
     - sample

What does it give?

If we are talking about SEO optimization, then it would be useful for the site to have some other text on the main page (under the list of main posts), a description of the site itself, some kind of analytics, some kind of rating or other additional information for the user. And if we do it through a template, then we save the localization and formatting...


ps I tried to parse the template and applied the decompressFromBase64.thisPost.html function, but somehow it did not work out very well.

pictures don't work, styles don't apply, etc.

Do you understand what I mean and what it is for?

**Comment by kwchang0831** [comment]
Sounds like an enhancement to me.

We will need more concise examples / use cases, or PR is sincerely welcomed.
