### ISSUE TITLE
Shared images in .md

### ISSUE THREAD

**Issue by korzh875** [kwchang0831/svelte-QWER#67]
### Describe the bug

if I have shared pictures that are not in the blog/article-folder, but in the users/assets/providers/* folder

if I add them to .md file they only work in dev mode, how can i make them work in production?

example path to shared files
src="/user/assets/providers/soft/logo.png etc

p.s I don't want to do that like

import Logo from '$assets/providers/payments/logo.png';

### Reproduction

- add path to images to .md file from assets folder
- run a production build
- make sure you don't have shared pictures

### Logs

```shell
-
```

### System Info

```shell
-
```

### Additional Information

![image](https://user-images.githubusercontent.com/130793155/235107981-ee399574-345e-42fc-8d8e-862027ebc584.png)

**Comment by kwchang0831** [comment]
Given you have
```
/src/assets/providers/belatra-logo.png
```

In your `/user/blogs/example/index.md`
Use the following link to access the above image
```md
![BelatraLogo](/providers/belatra-logo.png)
```

The above link will translate to 
```html
<p><ImgZoom src="/providers/belatra-logo.png" alt="BelatraLogo" /></p>
```

You can check `/src/generated/assets.json` (after `pnpm dev` or `pnpm build`) to see all the images that are available to you.

This works both in dev and production mode.

**Comment by korzh875** [comment]
![BelatraLogo](/providers/soft/belatra-logo.png)   

![image](https://user-images.githubusercontent.com/130793155/235438636-9389775e-4b50-4e17-91f2-994dc4ed6fce.png)
![image](https://user-images.githubusercontent.com/130793155/235438830-d9bb75a5-7ae3-4294-a7a6-c908a6679590.png)

![BelatraLogo](/belatra-logo.png)   
![image](https://user-images.githubusercontent.com/130793155/235438679-083f4ac1-a493-4325-a9b6-85aaf6b33350.png)
![image](https://user-images.githubusercontent.com/130793155/235438848-021428a1-9e6b-4e73-9175-bfe66cb9fbc6.png)


user/assets/providers/soft/belatra-logo.png

Does not give the desired result.

cmd: pnpm dev

**Comment by kwchang0831** [comment]
Please provide your repo.

**Comment by kwchang0831** [comment]
I have updated example post to show
https://svelte-qwer.vercel.app/example#image

Please update your svelte-QWER and QWER to the latest version to see if your issue remains

**Comment by korzh875** [comment]
![image](https://user-images.githubusercontent.com/130793155/235461329-242933d8-7b5e-4f5e-906f-9ae50ce63300.png)

![image](https://user-images.githubusercontent.com/130793155/235461790-9500d6dd-2fd3-42ef-9e37-03aa8e1b2328.png)


project is not working at all

these are the errors I get after a complete cleanup of the project and a new start

**Comment by korzh875** [comment]
where is the path formed? there is an assumption that the condition for different OS is not taken into account

**Comment by korzh875** [comment]
![image](https://user-images.githubusercontent.com/130793155/235466580-4e365b7d-3995-475f-ac49-6318227a047f.png)

**Comment by kwchang0831** [comment]
Thanks for reporting it. Haven't tested in Windows environment. 
It should be working now as of e568f1fc9aa900ee2e0d25971b10dbf35f45df63.

**Comment by kwchang0831** [comment]
If that's the default style you want, you can go ahead customize your image_zoom components at `src/lib/components/image_zoom.svelte` by removing `shadow-xl` in the `img` class.

```svelte
class="z-50 m-auto md:(rounded-2xl shadow-xl) {className ?? 'h-full w-auto aspect-auto object-cover'}"
```
