### ISSUE TITLE
Img Size

### ISSUE THREAD

**Issue by korzh875** [kwchang0831/svelte-QWER#69]
### Describe the bug

Prod:
![image](https://user-images.githubusercontent.com/130793155/235509726-2e6a3dc7-c728-4334-9e41-be43620dbdf9.png)
![image](https://user-images.githubusercontent.com/130793155/235509831-98a58f16-eac8-4a73-a956-2bf25a7bfc87.png)

Dev:
![image](https://user-images.githubusercontent.com/130793155/235509919-635f54e3-ee1e-43f3-817d-dc65ae79d99f.png)
![image](https://user-images.githubusercontent.com/130793155/235509974-53a63ecc-2d0b-465f-9854-09a1c62c09e1.png)

### Reproduction

If you use logotypes in png or svg format in dev mode, then everything works as expected

But if you run a prod assembly, then the svg become larger, and the png lose quality

### Logs

```shell
-
```

### System Info

```shell
-
```

**Comment by kwchang0831** [comment]
Please provide reproduction repo.

**Comment by korzh875** [comment]
restarted the versel without linking the repository and without changing npm to pnpm, then everything works for now
