### ISSUE TITLE
Google Pagespeed Performance 

### ISSUE THREAD

**Issue by korzh875** [kwchang0831/svelte-QWER#70]
Performance got worse

Please check

![image](https://user-images.githubusercontent.com/130793155/236688924-605a9a22-715c-4149-9743-fa502656ddee.png)

**Comment by korzh875** [comment]
![image](https://user-images.githubusercontent.com/130793155/236695980-b51f7cad-3e9c-4893-aa86-eeca2f58b84a.png)

and slug content

**Comment by kwchang0831** [comment]
Google Tag Manager was ran as service worker via PartyTown.
It was working and stopped working couple months ago, so I disabled PartyTown.
Apparently Google Tag Manager is affecting the score of performance.

**Comment by korzh875** [comment]
Maybe you should return PartyTown or look for an alternative?

**Comment by kwchang0831** [comment]
It is working as of 79213b93ea0c00f1ffa8a2f76829720b95352d2b.
