### ISSUE TITLE
Multiple tags not working

### ISSUE THREAD

**Issue by korzh875** [kwchang0831/svelte-QWER#71]
![image](https://github.com/kwchang0831/svelte-QWER/assets/130793155/87af4d6f-b0ce-42e5-8f83-8f30d678639b)

![image](https://github.com/kwchang0831/svelte-QWER/assets/130793155/a2838f7d-da38-4308-a10b-209646b70f72)

![image](https://github.com/kwchang0831/svelte-QWER/assets/130793155/79491ef1-9cfe-42a5-ac4f-61ef67eb3156)

So intended? because it violates the logic of the classical approach

**Comment by kwchang0831** [comment]
Not sure what classical approach is.
Tags work as intersection operation.

**Comment by korzh875** [comment]
why are you closing the thread?

tags don't work!

if I selected the tag "house" I was shown all the documents with this tag, if I selected another tag "garden", then I have to expand the list by adding documents with the tag "garden"

and get a list of documents tagged "garden" and "house"

**Comment by korzh875** [comment]
as you can see in the screenshots above, by selecting two tags, documents are not shown, although one tag is in one document, and the other tag is in another document

expected result that two documents will be visible

**Comment by korzh875** [comment]
https://www.amazon.com/s?k=apple&i=electronics&rh=n%3A493964%2Cp_89%3AApple%7CBelkin&dc&ds=v1%3ALsbTbEG%2FSc%2FbvgC3zZzzs28qd7zin9W4lC9ty2yS5BM&crid=1IUDSRZJ14GAS&qid=1683659677&rnid=2528832011&sprefix=apple%2Caps%2C253&ref=sr_nr_p_89_2

**Comment by kwchang0831** [comment]
Intersection meaning AND operation.

https://svelte-qwer.vercel.app/hello-QWER has the following tags: [[#Hello World](https://svelte-qwer.vercel.app/?tags=Hello%20World), [#QWER](https://svelte-qwer.vercel.app/?tags=QWER), [#2022](https://svelte-qwer.vercel.app/?tags-Year=2022), [#English](https://svelte-qwer.vercel.app/?tags-Language=English)]

https://svelte-qwer.vercel.app/example has the following tags: [[#Markdown](https://svelte-qwer.vercel.app/?tags=Markdown), [#2022](https://svelte-qwer.vercel.app/?tags-Year=2022), [#English](https://svelte-qwer.vercel.app/?tags-Language=English)]

There is no post satisfied BOTH "Hello World" AND "Markdown".

Tags is currently working as intended. 

If you are looking for OR operation or Union operation, you can either create a PR to let users select what kind of operation they desired or your can fork it and do it your way.
