### ISSUE TITLE
Search field is empty

### ISSUE THREAD

**Issue by korzh875** [kwchang0831/svelte-QWER#72]
### Describe the bug

After reload search field is empty

```
and do I understand correctly that the search looks for matches in all documents?

and if the word "example" is used in different documents, then the search will return several documents?
and do I understand correctly that the search looks for matches in all documents?

and if the word "example" is used in different documents, then the search will return several documents?
``` 

### Reproduction

https://github.com/kwchang0831/svelte-QWER/assets/130793155/f5be50fe-7614-4076-ac4f-e67f27474fe9

### Logs

```shell
-
```

### System Info

```shell
-
```

**Comment by kwchang0831** [comment]
Search function searches everything in the posts.
![image](https://github.com/kwchang0831/svelte-QWER/assets/88667293/097bc693-73f3-4ad4-ba2c-8604d20b04a3)

**Comment by korzh875** [comment]
after reload, the parameters in the address bar remain, but there is no data in the input (20s in the screencast above)

**Comment by kwchang0831** [comment]
Search input is now syncing with url query parameter as of 16d35806415a048c2354ad68e241ca8feefa6f85.
Thanks for reporting it.
