### ISSUE TITLE
Found an error using the template

### ISSUE THREAD

**Issue by Ethanol48** [kwchang0831/svelte-QWER#86]
### Describe the bug

This bug doesn't break the website nor the construction of it.

### Create a project with the template

Go to Github and create a project using this repo as a template

### pnpm dev

Run a development server and enter in any article

### go to the end of the article

After the recommendations you will see a text saying `An error occurred: giscus is not installed on this repository` 

<img width="910" alt="Screenshot 2023-11-04 at 15 17 35" src="https://github.com/kwchang0831/svelte-QWER/assets/96821054/19646c4b-75ae-4f47-be97-b1cd9436da1e">

### Logs

```shell
No relevant logs found
```

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 316.76 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - ~/.nvm/versions/node/v20.7.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.7.0/bin/npm
    pnpm: 8.8.0 - ~/.nvm/versions/node/v16.20.2/bin/pnpm
    bun: 1.0.3 - ~/.bun/bin/bun
    Watchman: 2023.10.09.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 17.0
  npmPackages:
    @sveltejs/adapter-cloudflare: ^2.3.3 => 2.3.3 
    @sveltejs/adapter-netlify: 2.0.8 => 2.0.8 
    @sveltejs/adapter-node: 1.3.1 => 1.3.1 
    @sveltejs/adapter-static: 2.0.3 => 2.0.3 
    @sveltejs/adapter-vercel: 3.0.3 => 3.0.3 
    @sveltejs/kit: 1.27.1 => 1.27.1 
    svelte: ^4.2.2 => 4.2.2 
    vite: ^4.5.0 => 4.5.0 

Browser: Firefox v 119.0
```

**Comment by kwchang0831** [comment]
Check out 
https://github.com/kwchang0831/svelte-QWER/blob/2a5497afb8387da8f474f078d36f27500960b898/user/config/site.ts#L93-L107

Generate your own using https://giscus.app/ , and update the config accordingly.
